// Realistic Indian Tech Jobs Dataset
// 60 jobs with realistic companies, roles, and details

const jobsData = [
    // Internships & Fresher roles
    {
        id: "job_001",
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Python", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://amazon.jobs/en/jobs/intern-sde",
        description: "Join Amazon's engineering team as a Software Development Engineer Intern. Work on real-world projects impacting millions of customers. Collaborate with experienced engineers and learn industry best practices. Strong problem-solving skills and knowledge of data structures required."
    },
    {
        id: "job_002",
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Web Development", "Communication"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3.6–4 LPA",
        applyUrl: "https://infosys.com/careers/get",
        description: "Infosys is hiring fresh graduates for our comprehensive training program. You'll undergo intensive training in modern technologies followed by deployment on client projects. Excellent opportunity to kickstart your IT career with a global leader. Strong academic background preferred."
    },
    {
        id: "job_003",
        title: "Frontend Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "HTML", "CSS", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://razorpay.com/jobs/frontend-intern",
        description: "Build beautiful, responsive interfaces for India's leading payment gateway. Work with React and modern frontend tools. Collaborate with designers and backend engineers. 6-month internship with potential for full-time conversion. Portfolio of projects required."
    },
    {
        id: "job_004",
        title: "QA Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java", "API Testing"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://flipkart.com/careers/qa-intern",
        description: "Join Flipkart's Quality Assurance team to ensure our platform delivers exceptional user experience. Learn automated testing, API testing, and quality processes. Work on India's largest e-commerce platform. Basic programming knowledge required."
    },
    {
        id: "job_005",
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel", "Data Visualization"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://swiggy.com/careers/data-analyst",
        description: "Analyze food delivery data to drive business decisions. Create dashboards, perform statistical analysis, and present insights to stakeholders. Work with real-time data from millions of orders. Strong analytical skills and SQL proficiency required."
    },
    {
        id: "job_006",
        title: "Python Developer (Fresher)",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Python", "Django", "REST API", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://tcs.com/careers/python-dev",
        description: "Develop backend applications using Python and Django framework. Work on enterprise projects for global clients. TCS offers excellent training and career growth opportunities. Freshers with strong Python fundamentals are encouraged to apply."
    },
    {
        id: "job_007",
        title: "Java Developer (0-1 years)",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Microservices", "SQL"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "4–6 LPA",
        applyUrl: "https://wipro.com/careers/java-developer",
        description: "Build scalable microservices using Java and Spring Boot. Work with experienced architects and learn enterprise development practices. Wipro provides comprehensive training and mentorship. Knowledge of object-oriented programming is essential."
    },
    {
        id: "job_008",
        title: "React Developer (Fresher)",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "JavaScript", "Redux", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "4–6 LPA",
        applyUrl: "https://zoho.com/careers/react-dev",
        description: "Join Zoho's frontend team to build world-class SaaS products. Work on complex React applications used by millions globally. Excellent learning environment with focus on product engineering. Strong JavaScript fundamentals required."
    },
    {
        id: "job_009",
        title: "Backend Developer Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Spring", "MySQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://phonepe.com/careers/backend-intern",
        description: "Build high-performance backend systems for India's fastest-growing fintech app. Work with microservices, databases, and distributed systems. Learn from experienced engineers handling millions of transactions daily. Strong coding skills required."
    },
    {
        id: "job_010",
        title: "Full Stack Intern",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "Node.js", "MongoDB", "JavaScript"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "₹40k–₹60k/month Internship",
        applyUrl: "https://cred.club/careers/fullstack-intern",
        description: "Work on CRED's premium fintech platform. Build features end-to-end from frontend to backend. Collaborate with designers and product managers. Fast-paced startup environment with high ownership. Portfolio demonstrating full-stack skills required."
    },

    // 1-3 years experience
    {
        id: "job_011",
        title: "React Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "TypeScript", "Redux", "Jest"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–12 LPA",
        applyUrl: "https://freshworks.com/careers/react-developer",
        description: "Build modern SaaS applications used by Fortune 500 companies. Work with React, TypeScript, and cutting-edge frontend technologies. Freshworks offers great work-life balance and learning opportunities. 1-3 years of React experience required."
    },
    {
        id: "job_012",
        title: "Backend Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Kafka", "PostgreSQL"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "10–15 LPA",
        applyUrl: "https://paytm.com/careers/backend-engineer",
        description: "Design and develop scalable backend services for Paytm's payment platform. Work with distributed systems, message queues, and high-throughput APIs. Handle millions of transactions with reliability and performance. Strong Java and system design skills needed."
    },
    {
        id: "job_013",
        title: "Frontend Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "JavaScript", "CSS", "Webpack"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "9–14 LPA",
        applyUrl: "https://juspay.in/careers/frontend",
        description: "Build payment interfaces for leading Indian e-commerce platforms. Work remotely with a talented team. Focus on performance, accessibility, and user experience. Juspay offers competitive compensation and flexible work culture. Strong frontend fundamentals essential."
    },
    {
        id: "job_014",
        title: "DevOps Engineer",
        company: "Accenture",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["AWS", "Docker", "Kubernetes", "Jenkins"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "7–11 LPA",
        applyUrl: "https://accenture.com/careers/devops",
        description: "Manage cloud infrastructure and CI/CD pipelines for enterprise clients. Work with AWS, containerization, and automation tools. Accenture provides exposure to diverse projects and technologies. Experience with cloud platforms and scripting required."
    },
    {
        id: "job_015",
        title: "Data Engineer",
        company: "Capgemini",
        location: "Pune",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "Spark", "Hadoop", "SQL"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "8–12 LPA",
        applyUrl: "https://capgemini.com/careers/data-engineer",
        description: "Build data pipelines and ETL processes for large-scale analytics. Work with big data technologies and cloud platforms. Capgemini offers global exposure and career advancement. Knowledge of distributed computing frameworks required."
    },
    {
        id: "job_016",
        title: "Mobile Developer (Android)",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "MVVM", "REST API"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        applyUrl: "https://swiggy.com/careers/android-dev",
        description: "Develop features for Swiggy's Android app used by millions daily. Work with modern Android architecture and best practices. Fast-paced environment with high impact. 1-3 years of Android development experience required."
    },
    {
        id: "job_017",
        title: "QA Automation Engineer",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Selenium", "Java", "TestNG", "API Testing"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "6–10 LPA",
        applyUrl: "https://cognizant.com/careers/qa-automation",
        description: "Automate testing for enterprise applications. Design test frameworks and ensure quality standards. Cognizant offers stability and diverse project opportunities. Experience with automation tools and frameworks essential."
    },
    {
        id: "job_018",
        title: "Full Stack Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Node.js", "PostgreSQL", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://razorpay.com/careers/fullstack",
        description: "Own features end-to-end in Razorpay's payment platform. Work with modern tech stack and agile methodologies. High-growth fintech with excellent compensation and ESOPs. Strong full-stack development experience required."
    },
    {
        id: "job_019",
        title: "Machine Learning Engineer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "TensorFlow", "ML Algorithms", "SQL"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "11–17 LPA",
        applyUrl: "https://flipkart.com/careers/ml-engineer",
        description: "Build ML models for personalization, search, and recommendations. Work with large-scale data and production ML systems. Flipkart offers challenging problems and cutting-edge technology. Background in machine learning and Python required."
    },
    {
        id: "job_020",
        title: "Cloud Engineer",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["AWS", "Azure", "Terraform", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "8–13 LPA",
        applyUrl: "https://ibm.com/careers/cloud-engineer",
        description: "Design and implement cloud solutions for enterprise clients. Work with multi-cloud environments and infrastructure as code. IBM provides excellent training and certification opportunities. Cloud platform experience essential."
    },

    // 3-5 years experience
    {
        id: "job_021",
        title: "Senior Backend Developer",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Java", "Microservices", "AWS", "DynamoDB"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "25–35 LPA",
        applyUrl: "https://amazon.jobs/en/jobs/senior-backend",
        description: "Lead backend development for Amazon's e-commerce platform. Design scalable microservices handling millions of requests. Mentor junior engineers and drive technical excellence. 3-5 years of backend development with strong system design skills required."
    },
    {
        id: "job_022",
        title: "Senior Frontend Engineer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["React", "TypeScript", "Performance Optimization", "Testing"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "22–32 LPA",
        applyUrl: "https://phonepe.com/careers/senior-frontend",
        description: "Build high-performance frontend for India's leading fintech app. Focus on performance, accessibility, and user experience. Lead technical initiatives and mentor team members. Strong React and TypeScript expertise required."
    },
    {
        id: "job_023",
        title: "Tech Lead - Full Stack",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["React", "Node.js", "System Design", "Leadership"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "30–45 LPA",
        applyUrl: "https://cred.club/careers/tech-lead",
        description: "Lead a team building CRED's premium fintech features. Own technical architecture and drive engineering excellence. Work closely with product and design. High ownership and impact. 3-5 years with proven leadership experience required."
    },
    {
        id: "job_024",
        title: "Senior Data Scientist",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Python", "Machine Learning", "Statistics", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "20–30 LPA",
        applyUrl: "https://swiggy.com/careers/senior-ds",
        description: "Drive data science initiatives for delivery optimization and personalization. Build ML models impacting millions of users. Work with large-scale data and production systems. Strong background in statistics and machine learning essential."
    },
    {
        id: "job_025",
        title: "Senior DevOps Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        skills: ["Kubernetes", "AWS", "Terraform", "Monitoring"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "18–28 LPA",
        applyUrl: "https://razorpay.com/careers/senior-devops",
        description: "Manage infrastructure for high-traffic payment systems. Ensure reliability, scalability, and security. Lead DevOps initiatives and automation. Remote work with flexible hours. 3-5 years of DevOps experience required."
    },

    // More diverse roles
    {
        id: "job_026",
        title: "Junior Backend Developer",
        company: "Oracle",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring", "Oracle DB", "REST API"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "5–8 LPA",
        applyUrl: "https://oracle.com/careers/backend-junior",
        description: "Develop enterprise applications using Java and Oracle technologies. Work on cloud-based solutions for global clients. Oracle offers excellent benefits and career stability. Fresh graduates with strong Java skills welcome."
    },
    {
        id: "job_027",
        title: "Frontend Developer",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Angular", "TypeScript", "SAPUI5", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "9–14 LPA",
        applyUrl: "https://sap.com/careers/frontend",
        description: "Build enterprise UI applications using Angular and SAP technologies. Work on products used by Fortune 500 companies. SAP provides excellent work-life balance and benefits. Experience with Angular framework required."
    },
    {
        id: "job_028",
        title: "Python Developer",
        company: "Dell",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "Flask", "MongoDB", "REST API"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "7–11 LPA",
        applyUrl: "https://dell.com/careers/python-dev",
        description: "Develop backend services for Dell's internal tools and platforms. Work with Python, databases, and cloud technologies. Stable work environment with global exposure. 1-3 years of Python development experience needed."
    },
    {
        id: "job_029",
        title: "Mobile Developer (iOS)",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Swift", "iOS SDK", "UIKit", "REST API"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        applyUrl: "https://flipkart.com/careers/ios-dev",
        description: "Build features for Flipkart's iOS app. Work with modern iOS development practices and architecture. High-impact role affecting millions of users. 1-3 years of iOS development experience required."
    },
    {
        id: "job_030",
        title: "Data Analyst",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["SQL", "Python", "Tableau", "Excel"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "6–10 LPA",
        applyUrl: "https://paytm.com/careers/data-analyst",
        description: "Analyze payment and user data to drive business insights. Create dashboards and reports for stakeholders. Work with large datasets and visualization tools. Strong SQL and analytical skills required."
    },
    {
        id: "job_031",
        title: "UI/UX Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["HTML", "CSS", "JavaScript", "Figma"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "https://zoho.com/careers/ui-ux-dev",
        description: "Implement designs for Zoho's SaaS products. Work closely with designers to create pixel-perfect interfaces. Focus on usability and accessibility. Experience with modern CSS and JavaScript required."
    },
    {
        id: "job_032",
        title: "Backend Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Remote",
        experience: "1-3",
        skills: ["Ruby on Rails", "PostgreSQL", "Redis", "AWS"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "8–13 LPA",
        applyUrl: "https://freshworks.com/careers/backend",
        description: "Develop backend services for Freshworks' SaaS platform. Work with Ruby on Rails and modern backend technologies. Remote-first culture with flexible hours. 1-3 years of backend development experience needed."
    },
    {
        id: "job_033",
        title: "Security Engineer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Security", "Penetration Testing", "Python", "Networking"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        applyUrl: "https://phonepe.com/careers/security",
        description: "Ensure security of PhonePe's payment platform. Conduct security audits, penetration testing, and vulnerability assessments. Work with engineering teams on secure coding practices. Background in cybersecurity essential."
    },
    {
        id: "job_034",
        title: "SRE Engineer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Linux", "Kubernetes", "Monitoring", "Python"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "9–15 LPA",
        applyUrl: "https://juspay.in/careers/sre",
        description: "Maintain reliability and performance of payment infrastructure. Monitor systems, respond to incidents, and improve automation. Work with distributed systems at scale. Strong Linux and scripting skills required."
    },
    {
        id: "job_035",
        title: "Graduate Engineer Trainee",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Problem Solving", "Communication"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "3.8–4.5 LPA",
        applyUrl: "https://capgemini.com/careers/get",
        description: "Join Capgemini's comprehensive training program for fresh graduates. Learn enterprise technologies and work on client projects. Global exposure and career growth opportunities. Strong academic record and aptitude required."
    },
    {
        id: "job_036",
        title: "Software Engineer",
        company: "TCS",
        location: "Kolkata",
        mode: "Onsite",
        experience: "0-1",
        skills: ["C++", "Java", "Data Structures", "Algorithms"],
        source: "Indeed",
        postedDaysAgo: 9,
        salaryRange: "3.5–5.5 LPA",
        applyUrl: "https://tcs.com/careers/software-engineer",
        description: "Develop software solutions for TCS's global clients. Work on diverse projects across industries. Comprehensive training and mentorship provided. Freshers with strong programming fundamentals encouraged to apply."
    },
    {
        id: "job_037",
        title: "Junior Java Developer",
        company: "Wipro",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring", "Hibernate", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "4–6.5 LPA",
        applyUrl: "https://wipro.com/careers/junior-java",
        description: "Build enterprise Java applications for global clients. Learn from experienced developers and work on real-world projects. Wipro offers structured career path and training. Knowledge of Java and frameworks required."
    },
    {
        id: "job_038",
        title: "React Native Developer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Redux", "Mobile Development"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "9–14 LPA",
        applyUrl: "https://swiggy.com/careers/react-native",
        description: "Develop cross-platform mobile features for Swiggy. Work with React Native and modern mobile development practices. Fast-paced environment with high impact. 1-3 years of React Native experience required."
    },
    {
        id: "job_039",
        title: "Backend Engineer (Go)",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Golang", "Microservices", "PostgreSQL", "Redis"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "12–20 LPA",
        applyUrl: "https://cred.club/careers/golang-backend",
        description: "Build high-performance backend services using Go. Work on CRED's fintech platform with focus on reliability and scale. Startup environment with high ownership. Experience with Go and distributed systems required."
    },
    {
        id: "job_040",
        title: "Test Automation Engineer",
        company: "Amazon",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Selenium", "Python", "CI/CD", "API Testing"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "8–13 LPA",
        applyUrl: "https://amazon.jobs/en/jobs/test-automation",
        description: "Automate testing for Amazon's services. Build test frameworks and ensure quality standards. Work with CI/CD pipelines and modern testing tools. 1-3 years of test automation experience needed."
    },
    {
        id: "job_041",
        title: "Full Stack Developer",
        company: "Accenture",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Angular", "Node.js", "MongoDB", "AWS"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "7–12 LPA",
        applyUrl: "https://accenture.com/careers/fullstack",
        description: "Develop full-stack applications for enterprise clients. Work with MEAN/MERN stack and cloud platforms. Accenture offers diverse projects and learning opportunities. 1-3 years of full-stack development experience required."
    },
    {
        id: "job_042",
        title: "Data Engineer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Spark", "Hadoop", "Python", "Airflow"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        applyUrl: "https://flipkart.com/careers/data-engineer",
        description: "Build data pipelines for Flipkart's analytics platform. Work with big data technologies and cloud infrastructure. Process petabytes of data daily. Strong background in distributed computing required."
    },
    {
        id: "job_043",
        title: "iOS Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Swift", "SwiftUI", "iOS SDK", "REST API"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "10–15 LPA",
        applyUrl: "https://razorpay.com/careers/ios",
        description: "Build iOS applications for Razorpay's payment products. Work with modern iOS technologies and best practices. Remote work with flexible hours. 1-3 years of iOS development experience required."
    },
    {
        id: "job_044",
        title: "Backend Developer (Node.js)",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Node.js", "Express", "MongoDB", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "8–13 LPA",
        applyUrl: "https://paytm.com/careers/nodejs-backend",
        description: "Develop Node.js microservices for Paytm's platform. Work with high-traffic systems and modern backend technologies. Fast-paced fintech environment. Strong Node.js and JavaScript skills required."
    },
    {
        id: "job_045",
        title: "Cloud Architect",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["AWS", "Azure", "Solution Design", "Terraform"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "18–28 LPA",
        applyUrl: "https://ibm.com/careers/cloud-architect",
        description: "Design cloud solutions for enterprise clients. Work with multi-cloud environments and lead technical implementations. IBM offers excellent benefits and career growth. 3-5 years of cloud architecture experience required."
    },
    {
        id: "job_046",
        title: "Senior Full Stack Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "3-5",
        skills: ["React", "Java", "PostgreSQL", "System Design"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "15–22 LPA",
        applyUrl: "https://zoho.com/careers/senior-fullstack",
        description: "Lead full-stack development for Zoho's SaaS products. Design scalable systems and mentor junior developers. Work on products used by millions globally. 3-5 years with strong full-stack expertise required."
    },
    {
        id: "job_047",
        title: "Principal Engineer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["System Design", "Ruby on Rails", "Architecture", "Leadership"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "25–38 LPA",
        applyUrl: "https://freshworks.com/careers/principal-engineer",
        description: "Drive technical strategy and architecture for Freshworks products. Lead engineering teams and mentor senior developers. Work on complex distributed systems. 3-5 years with proven technical leadership required."
    },
    {
        id: "job_048",
        title: "Engineering Manager",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Leadership", "System Design", "Java", "Team Management"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "28–40 LPA",
        applyUrl: "https://phonepe.com/careers/engineering-manager",
        description: "Lead engineering teams building PhonePe's fintech platform. Drive technical excellence and team growth. Work on high-impact projects affecting millions. 3-5 years with management experience required."
    },
    {
        id: "job_049",
        title: "Senior Android Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        skills: ["Kotlin", "Android", "Architecture", "Performance"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "18–26 LPA",
        applyUrl: "https://juspay.in/careers/senior-android",
        description: "Build Android SDKs and applications for payment solutions. Focus on performance, security, and developer experience. Remote work with flexible hours. 3-5 years of Android development required."
    },
    {
        id: "job_050",
        title: "Staff Engineer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["System Design", "Distributed Systems", "Leadership", "Architecture"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "35–50 LPA",
        applyUrl: "https://cred.club/careers/staff-engineer",
        description: "Drive technical vision and architecture for CRED's platform. Work on complex distributed systems and lead technical initiatives. High ownership and impact. 3-5 years with exceptional technical depth required."
    },

    // Additional roles for variety
    {
        id: "job_051",
        title: "Software Developer Intern",
        company: "Cognizant",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Python", "SQL", "Problem Solving"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "₹15k–₹30k/month Internship",
        applyUrl: "https://cognizant.com/careers/intern",
        description: "Learn enterprise software development at Cognizant. Work on client projects with mentorship from experienced developers. 6-month internship with potential conversion. Strong academic background and coding skills required."
    },
    {
        id: "job_052",
        title: "Junior Frontend Developer",
        company: "Infosys",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["HTML", "CSS", "JavaScript", "React"],
        source: "Indeed",
        postedDaysAgo: 10,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://infosys.com/careers/frontend-junior",
        description: "Build user interfaces for enterprise applications. Learn modern frontend technologies and best practices. Infosys provides comprehensive training and global exposure. Freshers with frontend skills welcome."
    },
    {
        id: "job_053",
        title: "DevOps Intern",
        company: "Dell",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Linux", "Docker", "Git", "Scripting"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://dell.com/careers/devops-intern",
        description: "Learn DevOps practices and tools at Dell. Work with CI/CD pipelines, containerization, and cloud platforms. Hands-on experience with production systems. Basic Linux and scripting knowledge required."
    },
    {
        id: "job_054",
        title: "Backend Developer",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Oracle DB", "REST API"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "8–12 LPA",
        applyUrl: "https://oracle.com/careers/backend",
        description: "Develop enterprise backend systems using Java and Oracle technologies. Work on cloud-native applications for global clients. Oracle offers stability and excellent benefits. 1-3 years of Java development required."
    },
    {
        id: "job_055",
        title: "Frontend Engineer",
        company: "SAP",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Vue.js", "JavaScript", "TypeScript", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "9–14 LPA",
        applyUrl: "https://sap.com/careers/frontend-engineer",
        description: "Build enterprise UI using Vue.js and modern frontend technologies. Work on SAP's cloud products used globally. Excellent work-life balance and benefits. Experience with Vue.js or similar frameworks required."
    },
    {
        id: "job_056",
        title: "Machine Learning Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Machine Learning", "Statistics", "TensorFlow"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://amazon.jobs/en/jobs/ml-intern",
        description: "Work on ML projects at Amazon. Build models for recommendations, search, and personalization. Learn from world-class ML engineers. Strong foundation in machine learning and Python required."
    },
    {
        id: "job_057",
        title: "Product Engineer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Full Stack", "React", "Node.js", "Product Thinking"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        applyUrl: "https://swiggy.com/careers/product-engineer",
        description: "Own product features end-to-end at Swiggy. Work closely with product and design teams. Build features impacting millions of users. 1-3 years with full-stack and product mindset required."
    },
    {
        id: "job_058",
        title: "Site Reliability Engineer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Linux", "Kubernetes", "Python", "Monitoring"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "9–15 LPA",
        applyUrl: "https://flipkart.com/careers/sre",
        description: "Ensure reliability of Flipkart's e-commerce platform. Monitor systems, automate operations, and improve performance. Work with large-scale distributed systems. Strong Linux and scripting skills required."
    },
    {
        id: "job_059",
        title: "Blockchain Developer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Blockchain", "Solidity", "Web3", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "10–16 LPA",
        applyUrl: "https://paytm.com/careers/blockchain",
        description: "Build blockchain solutions for Paytm's fintech platform. Work with smart contracts and decentralized applications. Emerging technology with high growth potential. Experience with blockchain technologies required."
    },
    {
        id: "job_060",
        title: "Technical Writer",
        company: "Zoho",
        location: "Chennai",
        mode: "Remote",
        experience: "1-3",
        skills: ["Technical Writing", "Documentation", "API Documentation", "Communication"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "5–9 LPA",
        applyUrl: "https://zoho.com/careers/tech-writer",
        description: "Create technical documentation for Zoho's products. Write API docs, user guides, and developer resources. Work remotely with engineering teams. 1-3 years of technical writing experience required."
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = jobsData;
}
