// KodNest Premium - Build System Router

/**
 * Global Configuration & State
 */
let currentFilters = {
    keyword: '',
    location: '',
    mode: '',
    experience: '',
    source: '',
    sort: 'latest',
    showOnlyMatches: false,
    status: ''
};

const routes = {
    '/': { step: 1, title: 'Project Overview', subtitle: 'Strategic planning for the Job Notification Tracker.', content: renderLandingPage },
    '/dashboard': { step: 2, title: 'Discovery Dashboard', subtitle: 'Analyzing market opportunities and live job data.', content: renderDashboardPage },
    '/saved': { step: 3, title: 'Strategic Bookmarks', subtitle: 'Curating high-value roles for focused application.', content: renderSavedPage },
    '/digest': { step: 4, title: 'Automated Intelligence', subtitle: 'Daily summary generated by the matching engine.', content: renderDigestPage },
    '/settings': { step: 5, title: 'Logic Configuration', subtitle: 'Fine-tuning the weighted matching parameters.', content: renderSettingsPage },
    '/jt/07-test': { step: 6, title: 'Quality Assurance', subtitle: 'Verifying core functional requirements and edge cases.', content: renderTestingPage },
    '/jt/08-ship': { step: 7, title: 'Final Deployment', subtitle: 'Preparing the application for production state.', content: renderShipPage },
    '/jt/proof': { step: 8, title: 'Submission Proof', subtitle: 'Final evidence collection and project archival.', content: renderProofPage }
};

/**
 * Storage Helpers
 */
const getPreferences = () => JSON.parse(localStorage.getItem('jobTrackerPreferences') || '{"roleKeywords":[],"minMatchScore":40}');
const savePreferences = (p) => localStorage.setItem('jobTrackerPreferences', JSON.stringify(p));
const getTestsPassed = () => JSON.parse(localStorage.getItem('jobTrackerTests') || '[]');
const getSubmissionLinks = () => JSON.parse(localStorage.getItem('jobTrackerLinks') || '{"lovable":"","github":"","live":""}');
const getJobStatus = (id) => JSON.parse(localStorage.getItem('jobTrackerStatus') || '{}')[id] || 'Not Applied';
const getSavedJobs = () => JSON.parse(localStorage.getItem('savedJobs') || '[]');

/**
 * Global Actions
 */
window.setJobStatus = (id, status) => {
    const s = JSON.parse(localStorage.getItem('jobTrackerStatus') || '{}');
    s[id] = status;
    localStorage.setItem('jobTrackerStatus', JSON.stringify(s));
    showToast(`Status: ${status}`);
    renderRoute();
};

window.toggleSaveJob = (id) => {
    let s = getSavedJobs();
    if (s.includes(id)) s = s.filter(x => x !== id); else s.push(id);
    localStorage.setItem('savedJobs', JSON.stringify(s));
    renderRoute();
};

window.setTestStatus = (id, checked) => {
    let p = getTestsPassed();
    if (checked) { if (!p.includes(id)) p.push(id); } else { p = p.filter(x => x !== id); }
    localStorage.setItem('jobTrackerTests', JSON.stringify(p));
    renderRoute();
};

window.saveSubmissionLink = (id, val) => {
    const l = getSubmissionLinks();
    l[id] = val;
    localStorage.setItem('jobTrackerLinks', JSON.stringify(l));
    renderRoute();
};

window.generateTodayDigest = () => {
    const jobs = jobsData.map(j => ({ ...j, matchScore: calculateMatchScore(j) }));
    const digest = jobs.sort((a, b) => b.matchScore - a.matchScore).slice(0, 10);
    localStorage.setItem(`jobTrackerDigest_${new Date().toISOString().split('T')[0]}`, JSON.stringify(digest));
    renderRoute();
};

/**
 * Core Logic
 */
function calculateMatchScore(job) {
    const p = getPreferences();
    if (!p.roleKeywords.length) return 0;
    let score = 0;
    const tl = job.title.toLowerCase();
    p.roleKeywords.forEach(kw => { if (tl.includes(kw.toLowerCase())) score += 25; });
    return Math.min(score, 100);
}

function getFilteredJobs() {
    let f = jobsData.map(j => ({ ...j, matchScore: calculateMatchScore(j), status: getJobStatus(j.id) }));
    if (currentFilters.status) f = f.filter(j => j.status === currentFilters.status);
    if (currentFilters.location) f = f.filter(j => j.location === currentFilters.location);
    if (currentFilters.showOnlyMatches) f = f.filter(j => j.matchScore >= getPreferences().minMatchScore);
    return f;
}

/**
 * Rendering Core
 */
function renderRoute() {
    const path = window.location.hash.slice(1) || '/';
    const route = routes[path] || routes['/'];

    document.title = `${route.title} - KodNest Premium`;

    // Progress
    document.getElementById('app-progress').textContent = `Step ${route.step} / 8`;

    // Status Badge
    const tests = getTestsPassed().length;
    const links = getSubmissionLinks();
    const isShipped = tests === 10 && links.lovable && links.github && links.live;
    const statusText = isShipped ? 'Shipped' : (tests > 0 ? 'In Progress' : 'Not Started');
    const statusClass = isShipped ? 'status--shipped' : (tests > 0 ? 'status--in-progress' : 'status--not-started');
    document.getElementById('app-status').innerHTML = `<span class="status-badge ${statusClass}">${statusText}</span>`;

    // Header
    document.getElementById('app-header').innerHTML = `<h1 class="context-header__title">${route.title}</h1><p class="context-header__subtitle">${route.subtitle}</p>`;

    // Content
    const { workspaceHtml, panelHtml } = route.content();
    document.getElementById('app-workspace').innerHTML = workspaceHtml;
    document.getElementById('app-panel').innerHTML = panelHtml;

    // Footer
    const items = [
        { label: 'UI Built', checked: true },
        { label: 'Logic Working', checked: getPreferences().roleKeywords.length > 0 },
        { label: 'Test Passed', checked: tests === 10 },
        { label: 'Deployed', checked: !!links.live }
    ];
    document.getElementById('app-footer').innerHTML = items.map(i => `<div class="checklist-item">${i.checked ? '☑' : '□'} ${i.label}</div>`).join('');

    // Nav Menu (In Workspace for Dash/Saved)
    if (['/dashboard', '/saved', '/digest', '/settings', '/jt/proof'].includes(path)) {
        const nav = `
            <div class="card" style="padding: 12px; margin-bottom: 24px; display: flex; gap: 16px; font-size: 14px;">
                <a href="#/" style="color: ${path === '/' ? 'var(--color-accent)' : 'inherit'}; text-decoration: none; font-weight: 500;">Home</a>
                <a href="#/dashboard" style="color: ${path === '/dashboard' ? 'var(--color-accent)' : 'inherit'}; text-decoration: none; font-weight: 500;">Dashboard</a>
                <a href="#/saved" style="color: ${path === '/saved' ? 'var(--color-accent)' : 'inherit'}; text-decoration: none; font-weight: 500;">Saved</a>
                <a href="#/digest" style="color: ${path === '/digest' ? 'var(--color-accent)' : 'inherit'}; text-decoration: none; font-weight: 500;">Digest</a>
                <a href="#/settings" style="color: ${path === '/settings' ? 'var(--color-accent)' : 'inherit'}; text-decoration: none; font-weight: 500;">Settings</a>
                <a href="#/jt/proof" style="color: ${path === '/jt/proof' ? 'var(--color-accent)' : 'inherit'}; text-decoration: none; font-weight: 500;">Proof</a>
            </div>
        `;
        document.getElementById('app-workspace').insertAdjacentHTML('afterbegin', nav);
    }

    initializeListeners();
}

/**
 * Pages
 */
function renderLandingPage() {
    return {
        workspaceHtml: `
            <div class="card">
                <h2 class="serif" style="font-size: 24px; margin-bottom: 16px;">KodNest Premium Build System</h2>
                <p>Welcome to the project command center. The Job Notification Tracker is currently active in the build environment.</p>
                <div style="margin-top: 24px; display: flex; gap: 12px;">
                    <a href="#/dashboard" class="btn btn--primary">Access Workspace</a>
                    <a href="#/settings" class="btn btn--secondary">Configure Logic</a>
                </div>
            </div>
        `,
        panelHtml: `<div class="card"><h3>Step 1: Planning</h3><p style="font-size: 14px; color: #666;">Initialize project and verify strategic objectives.</p></div>`
    };
}

function renderDashboardPage() {
    const jobs = getFilteredJobs();
    return {
        workspaceHtml: `
            <div style="margin-bottom: 24px; display: flex; gap: 12px; align-items: center;">
                <select id="filter-location" class="input" style="width: 200px;"><option value="">All Locations</option>${[...new Set(jobsData.map(j => j.location))].sort().map(l => `<option value="${l}" ${currentFilters.location === l ? 'selected' : ''}>${l}</option>`).join('')}</select>
                <label style="font-size: 14px;"><input type="checkbox" onchange="window.toggleMatchFilter(this.checked)" ${currentFilters.showOnlyMatches ? 'checked' : ''}> High Quality Only</label>
            </div>
            <div class="jobs-grid">${jobs.map(renderJobCard).join('')}</div>
        `,
        panelHtml: `<div class="card"><h3>Live Data</h3><p style="font-size: 14px; color: #666;">Analyzing ${jobs.length} roles found in tracking network.</p></div>`
    };
}

function renderJobCard(job) {
    const isSaved = getSavedJobs().includes(job.id);
    const statusClass = `status--${job.status.toLowerCase().replace(' ', '-')}`;
    return `
        <div class="card" style="margin-bottom: 16px;">
            <div style="display: flex; justify-content: space-between; align-items: flex-start;">
                <div><h4 class="serif">${job.title}</h4><p style="font-size: 14px; color: #666;">${job.company} • ${job.location}</p></div>
                <span class="status-badge" style="background:#EEE;">${job.source}</span>
            </div>
            <div style="margin-top: 12px; display: flex; gap: 8px;">
                <span class="status-badge ${statusClass}" style="font-size: 10px;">${job.status}</span>
                <span class="status-badge" style="font-size: 10px; background: #F0F4F8; color: #1E3A8A;">${job.matchScore || 0}% Match</span>
            </div>
            <div style="margin-top: 16px; display: flex; justify-content: space-between; align-items: center;">
                <div style="display: flex; gap: 4px;">
                    <button class="btn btn--secondary" style="padding: 4px 8px; font-size: 11px;" onclick="window.setJobStatus('${job.id}', 'Applied')">Applied</button>
                    <button class="btn btn--secondary" style="padding: 4px 8px; font-size: 11px;" onclick="window.setJobStatus('${job.id}', 'Rejected')">Rejected</button>
                </div>
                <div style="display: flex; gap: 8px;">
                    <button class="btn btn--secondary btn--small" onclick="window.toggleSaveJob('${job.id}')">${isSaved ? '❤️' : '🤍'}</button>
                    <button class="btn btn--primary btn--small" onclick="window.open('${job.applyUrl}','_blank')">Apply</button>
                </div>
            </div>
        </div>
    `;
}

function renderSettingsPage() {
    const p = getPreferences();
    return {
        workspaceHtml: `
            <div class="card">
                <div class="form-group" style="margin-bottom: 24px;"><label>Role Keywords</label><input type="text" id="pref-keywords" class="input" value="${p.roleKeywords.join(', ')}" placeholder="SDE, Frontend..."></div>
                <div class="form-group"><label>Threshold: <span id="threshold-val">${p.minMatchScore}%</span></label><input type="range" id="pref-threshold" min="0" max="100" value="${p.minMatchScore}" oninput="document.getElementById('threshold-val').textContent=this.value+'%'"></div>
                <button class="btn btn--primary" style="margin-top: 24px;" onclick="window.saveAllPrefs()">Save Configuration</button>
            </div>
        `,
        panelHtml: `<div class="card"><h3>Logic Controls</h3><p style="font-size: 14px; color: #666;">Adjusting these parameters re-calculates the match engine instantaneously.</p></div>`
    };
}

function renderTestingPage() {
    const passed = getTestsPassed();
    const items = [{ id: 't1', l: 'Persistence' }, { id: 't2', l: 'Matching' }, { id: 't3', l: 'Filtering' }, { id: 't4', l: 'Saving' }, { id: 't5', l: 'Linking' }];
    return {
        workspaceHtml: `<div class="card">${items.map(i => `<div style="padding:12px; border-bottom:1px solid #EEE;"><input type="checkbox" onchange="window.setTestStatus('${i.id}', this.checked)" ${passed.includes(i.id) ? 'checked' : ''}> ${i.l}</div>`).join('')}</div>`,
        panelHtml: `<div class="card"><h3>QA Check</h3><p>${passed.length} / 5 passed.</p><a href="#/jt/08-ship" class="btn btn--primary btn--small" style="width: 100%; margin-top: 16px;">Next: Ship</a></div>`
    };
}

function renderShipPage() {
    return { workspaceHtml: `<div class="card"><h2>Application Ready for Production.</h2><p>Click below to finalize project evidence.</p><a href="#/jt/proof" class="btn btn--primary" style="margin-top:16px;">Go to Proof</a></div>`, panelHtml: `<div class="card"><h3>Ready</h3></div>` };
}

function renderProofPage() {
    const links = getSubmissionLinks();
    return {
        workspaceHtml: `
            <div class="card">
                <div class="form-group" style="margin-bottom:16px;"><label>GitHub URL</label><input type="url" class="input" value="${links.github}" onchange="window.saveSubmissionLink('github', this.value)"></div>
                <div class="form-group" style="margin-bottom:16px;"><label>Live URL</label><input type="url" class="input" value="${links.live}" onchange="window.saveSubmissionLink('live', this.value)"></div>
                <button class="btn btn--primary" style="margin-top:16px;" onclick="window.copySubmission()">Copy Final Submission</button>
            </div>
        `,
        panelHtml: `<div class="card"><h3>Final Steps</h3><p style="font-size:14px; color:#666;">Provide project artifacts to complete shipment.</p></div>`
    };
}

function renderSavedPage() { return { workspaceHtml: `<div class="card"><h3>Strategic Bookmarks</h3><div class="jobs-grid">${getFilteredJobs().filter(j => getSavedJobs().includes(j.id)).map(renderJobCard).join('')}</div></div>`, panelHtml: `<div class="card"><h3>Saved</h3></div>` }; }
function renderDigestPage() { return { workspaceHtml: `<div class="card"><h3>Automated Intelligence</h3><p>Newsletter simulation goes here.</p><button class="btn btn--primary" onclick="window.generateTodayDigest()">Generate Digest</button></div>`, panelHtml: `<div class="card"><h3>9AM Trigger</h3></div>` }; }

/**
 * Global Interactivity
 */
window.saveAllPrefs = () => {
    const k = document.getElementById('pref-keywords').value.split(',').map(s => s.trim()).filter(s => s);
    const t = parseInt(document.getElementById('pref-threshold').value);
    savePreferences({ roleKeywords: k, minMatchScore: t });
    showToast("Preferences Saved");
    renderRoute();
};

window.toggleMatchFilter = (val) => { currentFilters.showOnlyMatches = val; renderRoute(); };

window.copySubmission = () => {
    const l = getSubmissionLinks();
    const txt = `Job Notification Tracker — Final Submission\n\nGitHub: ${l.github}\nLive: ${l.live}\n\nProcessed with KodNest Premium Build System.`;
    navigator.clipboard.writeText(txt).then(() => showToast("Copied!"));
};

function showToast(msg) {
    const t = document.createElement('div');
    t.style = "position: fixed; bottom: 80px; left: 50%; transform: translateX(-50%); background: #111; color: #FFF; padding: 10px 20px; border-radius: 4px; font-size: 14px; z-index: 1000;";
    t.textContent = msg;
    document.body.appendChild(t);
    setTimeout(() => document.body.removeChild(t), 2000);
}

/**
 * Init
 */
function initializeListeners() {
    document.getElementById('filter-location')?.addEventListener('change', e => { currentFilters.location = e.target.value; renderRoute(); });
}

window.addEventListener('hashchange', renderRoute);
window.addEventListener('DOMContentLoaded', renderRoute);
renderRoute();
